Vagrant.require_version ">= 1.7.0"

def set_vbox(vb, config)
  vb.gui = false
  vb.memory = 2048
  vb.cpus = 1
end

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "bento/ubuntu-16.04"

  private_count = 11
  (1..3).each do |mid|
    name = "k8s-m"
    config.vm.define "#{name}#{mid}" do |n|
      n.vm.hostname = "#{name}#{mid}"
      ip_addr = "192.16.35.#{private_count}"
      n.vm.network :private_network, ip: "#{ip_addr}", auto_config: true
      n.vm.provider :virtualbox do |vb, override|
        vb.name = "#{n.vm.hostname}"
        set_vbox(vb, override)
      end
      private_count += 1
    end
  end

  private_count = 21
  (1..3).each do |mid|
    name = "k8s-n"
    config.vm.define "#{name}#{mid}" do |n|
      n.vm.hostname = "#{name}#{mid}"
      ip_addr = "192.16.35.#{private_count}"
      n.vm.network :private_network, ip: "#{ip_addr}", auto_config: true
      n.vm.provider :virtualbox do |vb, override|
        vb.name = "#{n.vm.hostname}"
        set_vbox(vb, override)
      end
      private_count += 1
    end
  end
end
